# Generated by Django 5.0.6 on 2024-06-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('app', '0003_alter_user_managers_remove_user_date_joined_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='UserAdmin',
        ),
    ]
