# Generated by Django 5.0.6 on 2024-06-05 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_admin_useradmin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useradmin',
            table='user_admin',
        ),
    ]
