# Generated by Django 4.2.13 on 2024-06-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_user_is_stuff_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='child',
            field=models.CharField(default='', max_length=255, verbose_name='child'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.CharField(default='', max_length=255, verbose_name='parent'),
        ),
    ]
